[요구사항 1] 소피아 제출합니다. 😎
woowacourse-study/2022-looking-for-the-sound-of-an-object pull request #1
Opened 2022-04-10 12:23 UTC by soyi47

안녕하세요, 소피아입니다. 😊
요구사항 1 구현 끝! 제출합니다.

### [📢 객소찾 데모 페이지](https://soyi47.github.io/2022-looking-for-the-sound-of-an-object/)

<br >

### ✅ 요구사항 1 
아메리카노 하나만 나오는 자판기가 있다. 버튼을 누르면 디스펜서로 커피가 나온다.
(컵, 에스프레소, 뜨거운 물 이렇게 세 가지가 순서대로 나온다)

<br >

### 🤨 내가 들은 객체의 소리 
코드를 작성하기 전, 자판기에게 어떻게 역할을 나눌지, 무슨 역할을 하고 싶은지 물어봤습니다.
자판기는 자신 있게, 아메리카노 하나 정도는 주문 받는 것부터 만들어 내어주기까지 알아서 다 처리할 수 있다고 하더라고요.
그래서 자판기 혼자서 지금 다 하고 있습니다. 😁
작성하고 보니, 이번 요구사항 수준까지는 자판기 친구가 혼자 해도 될 것 같아요. 
그러나 여기서 메뉴가 더 추가되면 자판기가 혼자 다 하기에는 힘들지 않겠나 싶은데요. 
그 부분은 다음 요구사항을 받으면 다시 생각해보겠습니다.

<br >

### 🌸 그 외 
- 진짜 자판기 음료를 내어주는 듯한 UI면 좋겠지만, 그까진 여력이 없어서 추가되는 재료가 네모박스로 하나씩 순서대로 나타나도록 만들었습니다.
- 다음 음료를 뽑아가려면 내어준 음료를 가져가야 하므로, 추가 가져가기 버튼으로 나타난 재료 목록을 clear하도록 했어요.
- 또 사용자 가이드 메시지를 보여주도록 했습니다. 메뉴를 선택하라, 혹은 음료 준비 중, 음료 가져가라는 내용을 보여줍니다.
- 기능 구현 외에 다른 것들까지 신경 쓰면 힘들어질 것 같아 최대한 간단하게 진행하려고 했습니다.
때문에 webpack 안 쓰고 그냥 만들었고, css도 그냥 적었어요... 
이 부분은 다음 요구사항들을 진행하면서 조금씩 변경, 추가해볼게요!
- 요구사항 외의 조건이 모두 자유로워서 고민할 지점들이 많아지네요! 
다양한 시도를 해볼 수 있을 것 같아 좋습니다. 
샐리와 하리는 어떤 자판기를 만들었을지, 또 만들어갈지 기대되어요~ 😆

<br >

2022-04-11 14:33 UTC, liswktjs requested changes
샐리입니다 😎 태어나서 처음으로 해보는 코드 리뷰 떨리네요😳

데모 페이지에서 가져가기 버튼을 누르지 않고, 아메리카노 버튼만 계속 눌러봤는데요 
컵-에스프레소-뜨거운 물 element들이 계속 해서 쌓이게 되던데 혹시 의도 하신 건지 궁금하네요🤔
(또 저 혼자 생각해봤는데 안 가져갔는데 비워지는 것도 이상하긴 합니다😮)

제대로 된 리뷰를 한 건지는 스스로 의문이지만
확실한거는 제가 소피아 코드 읽어보면서 새로운거 몇개 얻어 갔습니다 :)
특히 $로 처리한 것 제가 냠냠 해보도록 하겠습니다😋
기억했다가 나중에 써먹겠습니다 후후 

몇 가지 궁금한 점 적어봤는데 답변을 달아주신다면 제가 많이 배워보겠습니다 🦻

2022-04-11 14:33 UTC, liswktjs commented on index.css
> +  justify-content: space-evenly;
flex의 속성값 사용해서 정렬한거 좋네요 👍👍

2022-04-11 14:33 UTC, liswktjs commented on src/VendingMachine.js
> +  }
Promise사용하셔서 then으로 처리한 거 좋네요! 👏👏 
보기도 깔끔하고 코드도 이해하기 쉬워요!👍
제가 Promise랑 별로 안 친해서 더 대단해 보여요👍

그런데 '컵' '에스프레소'같은 문자열 상수로 처리 안하신 이유가 있을까요? 사실 저같은 경우는 상수화 할때마다 어디까지 상수화 해야하는 건지 매번 고민했었는데 소피아 의견도 들어보고 싶어용!

2022-04-11 14:33 UTC, liswktjs commented on src/util.js
> +export const $$ = (selector, node = document) => node.querySelectorAll(selector);
black coffee 준이 생각나네요 ☕️ 

그런데  node로 바로 처리하는 방법 너무 신기해요! 👀
오호 이런 접근방법도 있었군요!  😆

코드 길이도 줄이고 보기도 편해서 좋아요 
이 방법 제가 냠냠 해보겠습니다 :)

2022-04-11 14:33 UTC, liswktjs commented on .eslintrc.json
> +  "globals": { "_": true },
오 이런 룰이 있었군요! 
혹시 왜 적용했는지 알 수 있을까요? 궁금하네요👀
소피아 덕분에 eslintrc 룰 새로운 거 익히고 갑니다:)

2022-04-11 14:33 UTC, liswktjs commented on index.html
> +        <button id="initialize-button" type="button">음료 가져가기</button>
음료 가져가기 버튼이 아메리카노가 다 나온 다음에 눌려지는 거니깐, take-beverage-button같은거 어떨까요? 
근데 또 역할 보면 초기화가 맞아서 어렵네요...🤔
소피아 마음대로 해주세요 하하👍

2022-04-11 15:13 UTC, soyi47 commented on src/VendingMachine.js
> +  }
저도 아직 비동기랑 안 친해서, 요 부분 깔끔하게 만들어본다고 조금 애먹었어요 ㅎㅅㅎ...

문자열을 상수로 안 만든 이유는, 아직 아메리카노 하나만 주문할 수 있다보니 재활용하는 곳이 없기도 하고,, 전체적으로 규모가 작은 앱이라, 굳이 상수로 빼주는 게 더 헷갈릴 수 있겠다는 생각에 그랬어요!
앱이 커지면서 일관성 면에서 비슷한 역할을 하는 값끼리 묶어주는 게 필요하거나, 재사용이 생기면 상수로 빼줄 것 같아요!

2022-04-11 15:15 UTC, soyi47 commented on src/util.js
> +export const $$ = (selector, node = document) => node.querySelectorAll(selector);
node 말고 target이라고 쓰기도 하더라고요~? 
저도 미션하면서 DOM 탐색을 줄일 수 있는 방법으로 피드백 때 제안 받으면서 사용하게 되었어요. 
냠냠하십쇼! 👍

2022-04-11 15:36 UTC, soyi47 commented on .eslintrc.json
> +  "globals": { "_": true },
오! 저도 이거 넣어둔 줄 몰랐어요. 하핳... 
그래서 한 번 찾아봤는데요! 사용자 전역 변수 관련 설정이라고 하네요. 
지금 전역 변수 관련 설정은 필요 없어서 지우겠습니다~

[Configuring - language options :: Eslint docs](https://eslint.org/docs/user-guide/configuring/language-options#specifying-globals)
[ESLint's "no-undef" rule is calling my use of Underscore an undefined variable :: Stack Overflow](https://stackoverflow.com/questions/34820817/eslints-no-undef-rule-is-calling-my-use-of-underscore-an-undefined-variable)

2022-04-11 16:31 UTC, soyi47 commented on index.html
> +        <button id="initialize-button" type="button">음료 가져가기</button>
이 부분은 저도 initialize가 좋을지 take-out이 좋을지.. 네이밍이 고민되더라고요. 😥
우선 take-out-button으로 수정할게요! https://github.com/woowacourse-study/2022-looking-for-the-sound-of-an-object/pull/1/commits/f4768a8e901a4de22129fec0832b3206efb942dc

2022-04-11 16:34 UTC, soyi47 commented
샐리 리뷰 감사해요! 👍

1. 아메리카노 버튼을 계속 누를 수 있어서 재료가 계속 쌓이는 부분은 의도한 거 아니고, 제가 방어 코드 작성을 놓친 부분이네요.
button에 disable 속성을 주는 코드를 추가했어요. https://github.com/woowacourse-study/2022-looking-for-the-sound-of-an-object/pull/1/commits/9a615262edf8a2e729f0b0925d0a797e3d9b781e

2. 또 전체적으로 색상이 마음에 안 들어서 조금 바꿔봤습니다. https://github.com/woowacourse-study/2022-looking-for-the-sound-of-an-object/pull/1/commits/19c8ca4a21466148caa30279a308ddc267495046

나머지도 코멘트 달아두었어요. 확인 부탁 드려요~ 🌸

2022-04-12 00:33 UTC, liswktjs approved these changes

2022-04-12 00:35 UTC, liswktjs commented on .eslintrc.json
> +  "globals": { "_": true },
오 링크까지 감사합니다 소피아:) 사용자 전역 변수 관련 설정도 할 수 있었군요!

2022-04-12 00:36 UTC, liswktjs commented on index.html
> +        <button id="initialize-button" type="button">음료 가져가기</button>
네이밍이 항상 제일 어려운 것 같아요 ㅠㅠㅠ 저도 항상 고민하는게 네이밍..

2022-04-12 01:40 UTC, merged