chore: 리액트 설치
woowacourse-study/2022-looking-for-the-sound-of-an-object pull request #16
Opened 2022-06-14 15:12 UTC by liswktjs

2022-06-19 09:54 UTC, soyi47 requested changes
샐리 하이~ ヾ(•ω•`)o
이번 리뷰를 맡은 소피아입니다. ❤

리액트로 옮겨오면서 UI가 새롭게 예뻐졌네요.
바쁠텐데 이번에도 재료 충전까지 챙겨준 거 멋져요 👍

1. 자판기 App이 왼쪽 상단 구석에 치우쳐져있는데, 가운데로 정렬해주면 한눈에 들어올 것 같아요!
2. 요구사항 1번에 재료가 순서대로 나온다는 내용이 있는데요. 지금은 재료가 순서대로 나오지 않고, 음료가 바로 나오네요. 😥 한번 확인해주세요~

방학이지만 많이 바쁠텐데,,, 
바로 반영해보기 힘든 부분은 확인 코멘트만 남기고 다음 요구사항 때 같이 수정해봐요~ 🥰

2022-06-19 09:54 UTC, soyi47 commented on src/App.js
> +    </BrowserRouter>
1. 이번에도 재료 충전까지...? 바쁘다면서 대단한 걸... 👍👍👍

2. `<BrowserRouter>`에 `basename`을 줄 수 있어요!
https://reactrouter.com/docs/en/v6/routers/browser-router

3. App 자체가 VendingMachine인 것 같은데, 메인으로 나타나는 컴포넌트 이름도 VendingMachine이네요..! 개인적으론 좀 아쉬운데, 샐리 생각엔 괜찮나요? 다른 네이밍은 없을까요~?

2022-06-19 09:54 UTC, soyi47 commented on src/components/common/Layout/Header.jsx
> +          </NavButton>
NavButton onClick에서 react-router의 navigate를 사용하네요.
a 태그를 사용할거면, react-router의 `Link` 컴포넌트에 스타일드를 적용하는 방식으로 사용해봐도 좋을 것 같아요! 그럼 useNavigate 없이 `Link`의 `to`를 바로 사용할 수 있습니다.

```
const NavButton = styled(Link)`
   ...
`;
```

2022-06-19 09:54 UTC, soyi47 commented on src/components/pages/VendingMachine/CoinInsert.jsx
> +`;
샐리가 생각하는 Container와 Wrapper의 차이는 어떻게 되나요~?

2022-06-19 09:54 UTC, soyi47 commented on src/modules/index.js
> +export default rootReducer;
폴더 이름을 어떤 이유로 modules라 지었나요~?

2022-06-19 09:54 UTC, soyi47 commented on src/modules/stock.js
> +};
1. switch case를 써도 깔끔하겠다는 생각이 듭니다.
2. 메뉴 가격처럼 메뉴 이름을 상수화 해보는 것도 좋겠네요. 휴먼 에러 방지..!

2022-06-19 09:54 UTC, soyi47 commented on src/modules/stock.js
> +};
음료 종류마다 action이 생기면, stock reducer 코드가 점점 더 커지겠어요!
메뉴 추가에 조금 더 쉽게 대응할 수 있는 방식이 있을지 고민해보면 좋을 것 같아요.
`action.payload`에서 차감할 재료 목록 또는 메뉴 정보를 받고, 그 재료 목록으로 상태 변경을 주는 방법도 있겠네요. 생각해보시죠~

2022-06-19 09:54 UTC, soyi47 commented on src/style/theme.js
> +};
컬러 상수화~ 👍

2022-06-19 09:54 UTC, soyi47 commented on src/components/pages/store/StockCharge.jsx
> +  );
재료 목록을 배열로 만들고 map으로 순회해주면 어떨까요?
천천히 리팩토링 ㄱㄱ~

2022-06-20 04:14 UTC, LAH1203 commented
아니 지나가다가 봤는데 샐리 자판기 UI 뭐야...? 너무 예쁘잖아........... 🙊

2022-06-20 05:01 UTC, merged

2022-06-25 12:54 UTC, liswktjs commented on src/components/pages/VendingMachine/CoinInsert.jsx
> +`;
컨테이너는 여러개의 컴포넌트를 감싸는 컴포넌트, 
Wrapper는 정말 스타일링을 위한 컴포넌트 네이밍으로 사용하고 있어요 ㅎㅎ

2022-06-25 12:55 UTC, liswktjs commented on src/modules/index.js
> +export default rootReducer;
리덕스는 다른 로직으로 교체될 수 있는 로직이니깐,
뭔가 moudle는 계속 갈아 끼울수 있는 독립적인 단위들을 의미하는 것 같아서 module로 네이밍 해봤습니당:)