[요구사항 6] 태태 제출합니다 🌕
woowacourse-study/2022-looking-for-the-sound-of-an-object pull request #17
Opened 2022-06-16 15:35 UTC by nan-noo

안녕하세요~~ 
스타일 적용하려다 시간이 부족해 버튼만 적용했습니다..ㅎㅎ

## 데모 페이지
[태태 자판기](https://nan-noo.github.io/2022-looking-for-the-sound-of-an-object/)
스토리북은 아직 작성하지 못했습니다..ㅎㅎ

## 소감
중간에 참여하게 되어 step6 요구사항까지 한 번에 받았지만, step1부터 차근차근 구현해보았습니다.
[step1 branch](https://github.com/nan-noo/2022-looking-for-the-sound-of-an-object/tree/step1)
[step2 branch](https://github.com/nan-noo/2022-looking-for-the-sound-of-an-object/tree/step2)
[step3 branch](https://github.com/nan-noo/2022-looking-for-the-sound-of-an-object/tree/step3)
[step4 branch](https://github.com/nan-noo/2022-looking-for-the-sound-of-an-object/tree/step4)
[step5 branch](https://github.com/nan-noo/2022-looking-for-the-sound-of-an-object/tree/step5)

그동안 미션을 할 때는 UI가 주어져서 컴포넌트를 만들 때 로직과 함께 UI를 고려했지만, 이번에는 주어진 UI 요소가 전혀 없어서 로직에 기반해서 컴포넌트를 분리했습니다.
매 요구사항마다 다음의 단계를 따라 진행했습니다.
1. 일단 실행되게 만든다.
2. 리팩토링한다.
    - 중복 로직 및 컴포넌트 분리

컴포넌트 분리 기준
- 여러 관심사 로직이 한 컴포넌트 내에 있으면 분리
  209dacc09b976663ca0a258a9f71d586bb9e1e9d : App.jsx에 dispenser 관련 로직과 inputMoney 관련 로직이 함께 있음 -> 투입 및 반환 섹션은 dispenser로직을 사용하지 않음 -> dispenser로직을 사용하는 컴포넌트를 분리 -> App.jsx는 현재 전역 상태인 inputMoney만 갖고 있고, DrinkSection이 dispenser로직을 가짐

작은 기능부터 만들다보니 확장성을 크게 고려하지 않았지만, 자연스럽게 확장성을 가지게 되는 느낌(?)이 들었습니다. step1에 dispenser 로직 짜는 게 가장 오래 걸렸고, step2~6까지는 오래 걸리지 않았습니다 :D 덕분에 재밌게 구현했네요.

잘 부탁드려요!!

2022-06-19 04:07 UTC, LAH1203 requested changes
아이쿠 유명하신 하산 태태의 리뷰를 하게 되다니,, 영광입니다~😆

<br />

---

<br />

우선 여러 가지 시도해보며 발견한 오류가 있어서 적어볼까 해요.

1.
<img width="989" alt="image" src="https://user-images.githubusercontent.com/57928612/174463173-a0bfea0b-34d7-4969-9427-cd62bf19630c.png">

에러 메시지에서는 최대 50,000원까지 투입이 가능하다고 하는데, 막상 50,000원을 넣으려고 하면 에러 메시지가 나오더라고요! 이 부분은 통합이 필요할 것 같습니당~

2.
<img width="160" alt="image" src="https://user-images.githubusercontent.com/57928612/174463353-c733703a-e7ac-4775-8859-f1ae81ab413c.png">

음료를 받기 전에 한 번 더 금액을 넣고 환불하기를 누르면 금액이 50,000원 이상인데도 위 이미지처럼 가능하더라고요! 막상 금액이 50,000원 이상일 때는 `더이상 금액을 넣을 수 없습니다(최대 50,000원).`이라는 에러 메시지가 출력이 되고요. 이 부분도 통일이 필요하지 않을까 싶어요!

3.
(이 부분은 너무 빨라서 이미지 캡처를 못했네요ㅎㅎ.. 텍스트로만 적어봅니당)
음료 받기를 누르고 음료가 나오는 중에도 자판기 버튼을 누르기가 가능한데, 이렇게 하면 디스펜서로 음료가 나오지 않아도 이 자판기 친구가 돈을 먹어요 🙊

<br />

우선은 에러는 이 정도 발견한 것 같습니당,, 만약에 추후 다른 에러가 발견되면 그 때 추가적으로 코멘트 남기도록 할게요!

<br />

---

<br />

그 외에 코드 레벨에서의 피드백은 개별 코멘트로 남길게요!
(사실 별로 피드백할 게 없어서 짜내기 힘들었음다,, 영양가 없어도 이해해주세요 😭)

p.s. 태태의 TS 자판기도 너무 궁금해요! 다음 번엔 기대해도 되나요?

2022-06-19 04:07 UTC, LAH1203 commented on .prettierrc.json
> +  "importOrder": [
오호 저는 import 정렬을 eslint에서 해주었는데 prettier에서도 가능하군요! 👏

2022-06-19 04:07 UTC, LAH1203 commented on README.md
> +- [태태](https://github.com/nan-noo)
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ태태 귀여웡,,😚

2022-06-19 04:07 UTC, LAH1203 commented on public/index.html
> +<html lang="en">
오 `en`이네요! 의도하신 걸까요, 아님 미처 보지 못하신 걸까요? 🤔

2022-06-19 04:07 UTC, LAH1203 commented on public/index.html
> +    <meta name="description" content="태태의 '객체의 소리를 찾아서' 자판기" />
이런 깨알같은 description 좋아요! 👏

2022-06-19 04:07 UTC, LAH1203 commented on src/components/App.jsx
> +        setInputMoney={setInputMoney}
이렇게 상태를 변경할 수 있는 setState 함수를 바로 전달해도 괜찮은 걸까요?

2022-06-19 04:07 UTC, LAH1203 commented on src/components/DrinkSection/index.jsx
> +          <p key={index}>{action}</p>
키로 index를 주신 이유가 있을까요?

2022-06-19 04:07 UTC, LAH1203 commented on src/constants/index.js
> +export const COIN_UNIT = {
보면 500-500, 100-100, 50-50, 10-10 이렇게 key와 value가 같은데도 `COIN_UNIT`이라는 새로운 Object로 구성하여 사용해주신 이유가 있을까요~?

2022-06-19 04:07 UTC, LAH1203 commented on src/hooks/useHandleDispenser.js
> +export const useHandleDispenser = (timeInterval) => {
진짜 섹시하게 사용하셨네요,, 배워갑니다 🥹

2022-06-19 04:07 UTC, LAH1203 commented on src/components/MoneySection/InsertMoneySection.jsx
> +  const InsertMoney = () => {
다시 보다보니 발견 👀

2022-06-19 13:12 UTC, nan-noo commented on public/index.html
> +<html lang="en">
깜박했습니다 ㅎㅎ..

2022-06-19 14:20 UTC, LAH1203 reviewed
아무래도 리뷰에 좀 더 영양을 첨가해야 할 것 같아서 처음부터 끝까지 싹싹 뜯어봤습니다 👀
(저 이제 태태 코드 제거처럼 다 이해했어요~😄)

혹시 merge 받고 다음 단계에서 요구사항이랑 같이 피드백을 반영하거나 고치고 싶으시다면 코멘트나 디엠 남겨주세용 🤗

2022-06-19 14:20 UTC, LAH1203 commented on src/components/DrinkSection/DrinkButtonSection.jsx
> +      window.confirm(`음료가 나오면 환불할 수 없습니다. 음료를 받으시겠습니까?`)
개인적으로 저는 이렇게 조건에 맞는 동작을 수행시킬 때 조건에 맞지 않을 경우에 return을 시키고 if문 밖에서 해당 동작을 수행시키곤 해요.
전체적으로 어떨 땐 early return을 시키고 어떨 땐 안 하고 있는 것 같은데, 하나로 통일시켜보는건 어떨까요?

2022-06-19 14:20 UTC, LAH1203 commented on src/components/App.jsx
> +      <ReturnMoneySection
`DrinkSection`에서는 index.jsx에서 여러 섹션을 묶어줬는데, `InsertMoneySection`과 `ReturnMoneySection`은 같은 `MoneySection` 폴더에 있어도 App.jsx에서 따로 가져와서 사용하네요..!
이 친구도 한 번 index.jsx에서 묶어주어 `MoneySection`으로 사용하는 건 어떤가요?

2022-06-19 14:20 UTC, LAH1203 commented on src/hooks/useHandleDispenser.js
> +        setDispenserAction((prev) => [...prev, ingredient]);
`handleDispenser`에서는 (재료 포함) dispenser action을 받아서 이를 dispenserAction에 저장하는거죠?
그럼 `ingredient` 대신 다른 이름은 어떨까요? 재료를 dispenserAction에 저장하면 이를 가공해서 보여주나 보다 생각하고 사용하는 곳을 봤더니 `{action}`으로 그냥 바로 보여주더라고요.
(혹시 제가 잘못 이해한거라면 알려주세요! 🙂)

2022-06-19 14:20 UTC, LAH1203 commented on src/components/DrinkSection/DrinkButtonSection.jsx
> +      setDispenserAction([]);
`handleDispenser`가 `setDispenserAction`을 조작하는 아이이고, 막상 사용하는 다른 곳(여기)에서도 전달받은 `setDispenserAction`을 dispenserAction을 리셋하는 용도로만 사용하는 것 같더라고요!
그럼 커스텀훅에서 `setDispenserAction`을 반환하는 것보단 `resetDispenserAction`을 만들어 반환하는 건 어떻게 생각하시나요? 일관성 있고 더 안전하게 사용할 수 있을 것 같아요 😊

2022-06-20 03:45 UTC, nan-noo commented on src/components/App.jsx
> +        setInputMoney={setInputMoney}
기능상 문제는 없다고 보는데, 찾아보니 setState의 기능이 광범위해서 범위를 좁히는 게 낫다고 하네용! + 유지보수가 쉬움. 예를 들어, setInputMoney 대신에 handleInputMoneyChange 등을 만들어서 부모에서 setState 타입을 수정해도 자식까지 수정할 필요 없게!
```js
const handleInputMoneyChange = (...) => {
   ...
   setInputMoney(...)
   ...
}
```

다음 단계에서 수정하겠습니당~~!!

2022-06-20 03:48 UTC, nan-noo commented on src/components/DrinkSection/index.jsx
> +          <p key={index}>{action}</p>
키를 안 주면 워닝이 떠서 index로 명시했습니다. 고유 아이디가 있으면 좋았겠지만, 지금 단계에선 index로 해도 큰 문제가 없어서(뒤에 붙이기 때문에!) 그냥 뒀습니다.
```js
setDispenserAction((prev) => [...prev, ingredient]);
```

2022-06-20 03:54 UTC, nan-noo commented on src/constants/index.js
> +export const COIN_UNIT = {
예전에 저도 하리랑 같은 생각을 해서 객체로 만들지 않고 `COIN_500 = 500` 이런 식으로 했는데, 리뷰어분이 이건 왜 객체로 안했냐고 하시더라구요! 취향차이긴 한데, 이번에 이렇게 한 이유는 다른 상수도 다 객체로 해서 통일성을 주기 위해 해봤습니다!
이와 별개로 상수화는 꼭 해야 한다고 생각합니다. 지금은 key와 value 모두 won 단위지만, 화폐 단위가 달라지면 value가 달라질 수도 있고..(?) 암튼 그렇습니당 :D

2022-06-20 03:55 UTC, nan-noo commented on src/hooks/useHandleDispenser.js
> +export const useHandleDispenser = (timeInterval) => {
ㅋㅋㅋㅋㅋㅋ 하리 표현 모야!!!

2022-06-20 03:56 UTC, nan-noo commented on src/components/MoneySection/InsertMoneySection.jsx
> +  const InsertMoney = () => {
오잉 뭘 발견한거죠!!! ref??

2022-06-20 03:57 UTC, nan-noo commented on src/components/DrinkSection/DrinkButtonSection.jsx
> +      window.confirm(`음료가 나오면 환불할 수 없습니다. 음료를 받으시겠습니까?`)
오 이것도 통일성 주는 게 좋아 보이네요
역시 하리

2022-06-20 03:59 UTC, nan-noo commented on src/components/App.jsx
> +      <ReturnMoneySection
아 이거 분리하려고 MoneySection 폴더를 만든건데, 막상 index.jsx에 분리하고 보니 depth만 깊어지고 아무 역할도 안 하더라구요!! 스타일링도 없고 그래서 일단 폴더에 옮겨만 놨습니당. 뭔가 기능이 더 많아지면 만들것 같아요!

2022-06-20 03:59 UTC, nan-noo commented on src/hooks/useHandleDispenser.js
> +        setDispenserAction((prev) => [...prev, ingredient]);
다른 곳에서는 다 action으로 썼는데 요거만 안 고쳤네요!! 고마워요ㅎㅎㅎ

2022-06-20 04:00 UTC, nan-noo commented
에러랑 피드백 준 것까지 모두 다음 단계 할 때 반영하겠습니다!!! 하리 천재만재똑똑이 도움 정말 많이 됐어요!!! @LAH1203

2022-06-20 04:01 UTC, nan-noo commented on src/components/DrinkSection/DrinkButtonSection.jsx
> +      setDispenserAction([]);
오 안정성까지 챙기는 하리..! 너무 좋은 생각입니다

2022-06-20 04:06 UTC, LAH1203 commented on src/components/MoneySection/InsertMoneySection.jsx
> +  const InsertMoney = () => {
아 제가 왜 이렇게만 쓰고 넘어갔죠..? ㅋㅋㅋㅋㅋㅋㅋ
`InsertMoney`가 함수인데 카멜 케이스가 아니라 파스칼 케이스여서 남겨봤습니당

2022-06-20 04:09 UTC, LAH1203 approved these changes
저도 태태 코드 보면서 새로운 걸 많이 배웠습니당 😆 이 맛에 코드 리뷰 하나 봅니다,, (대신 규모가 큰 건 진짜 못 하겠어요... 지금이 딱 적당쓰 🤪)
다음 번에 반영해주신다고 하셔서 바로 merge할게요! 수고 많으셨습니다 👏👏

2022-06-20 04:09 UTC, merged