[요구사항 6] 소피아 제출합니다 🌕
woowacourse-study/2022-looking-for-the-sound-of-an-object pull request #21
Opened 2022-06-17 14:58 UTC by soyi47

여러분들~ 상당히 오랜만입니다. ヾ(•ω•`)o
다들 즐거운 방학 보내고 계시죠~?

하산 태태 @nan-noo 선생님의 리뷰를 받게 되어 영광입니다. 🥰
그간 노느라 정말 리액트로 옮기고 컴포넌트 단위로 나누는 작업만 겨우 했습니다.
좀 더 수정하고 내고 싶지만 마감 기한이 다 되어서 제출부터 합니다. 😂

여유가 된다면 태태 선생님이 리뷰 주시기 전에 리팩토링 좀 해보겠습니다.
(주말에도 계속 일정이 있어서 가능할지는 모르겠네요 ㅠㅅㅠ)

<br >

### [🧃 데모 페이지 🧃](https://soyi47.github.io/2022-looking-for-the-sound-of-an-object/)

<br >

### 💡 상태 관리와 컴포넌트
- 상태 관리 라이브러리 따로 사용 안 했습니다. useCustomerCharge, useOrder라는 커스텀 훅을 만들고, 이 커스텀 훅을 자판기 자체(App.jsx)에서 사용하도록 했어요. 커스텀 훅으로 생성된 상태, 그리고 상태 관리 로직을 하위 컴포넌트에 props로 전달하도록 했습니다. 아직까진 props drilling이 깊다고 느껴지지는 않는데, props를 단순히 전달만 하는 상황들이 생기기는 해서 Context API를 사용할까 고민하고 있습니다.
- 아래와 같이 영역별로 나눠봤습니다.
컴포넌트 네이밍이 뭔가 찜찜하고 마음에 들지 않네요. -Section 이라는 표현이 너무 범용적이라 그런 것 같기도 하고, Section 앞에 붙은 표현들이 애매하게 느껴진달까요..? 리뷰어님이 보시기엔 어떤가요? 역할보다 영역 위주의 네이밍이라 그런 것 같은데, 더 괜찮은 이름 있으면 추천 부탁드립니다.
<img width="580" alt="제목 없음" src="https://user-images.githubusercontent.com/71116429/174330034-25290e9b-9fe1-4092-9ac7-71de914ac3b9.png">

---

1. TS 적용하기
2. SCSS 적용하기

이번 방학동안 위 두 가지를 목표로 하고 있어요. 남은 기간동안 목표 달성 해보겠습니다!

2022-06-20 06:03 UTC, nan-noo commented
머지부터 하겠습니당... 리뷰는 오늘까지 할테니 다음 스텝때 반영해주세요..!

2022-06-20 06:03 UTC, merged

2022-06-20 11:36 UTC, nan-noo requested changes
> 상태 관리 라이브러리 따로 사용 안 했습니다. props를 단순히 전달만 하는 상황들이 생기기는 해서 Context API를 사용할까 고민하고 있습니다.

저도 이거 고민중입니다! 꼭 전역 상태가 아니라도 drilling이 깊어지는 상황에선 부분적으로 사용해도 좋다고 생각해요!

> 아래와 같이 영역별로 나눠봤습니다. 컴포넌트 네이밍이 뭔가 찜찜하고 마음에 들지 않네요. 

저랑 비슷한 네이밍이라 전 좋았습니당 :D 아직까진 헷갈리는 부분도 없고, Section이 좀 걸린다면 폴더명 말고 파일명에선 Section을 없애도 괜찮지 않을까요?!

## 궁금한 점
금액 충전하는 부분은 input이 하나밖에 없는데, form으로 감싼 이유는 무엇인가요? form이 제공하는 유효성 검증이나 엔터 등을 쓰기 위해선가요??
 - https://www.w3schools.com/html/html_forms.asp

## 발견한 에러
잔돈반환을 성공한 후, 한 번 더 누르면 잔돈 받아가기 버튼을 누르지 않아도 잔돈이 0원으로 초기화됨
- 돈 2000 충전 후 잔돈 반환 -> 잔돈 2000
- 한 번 더 잔돈반환 클릭 -> 잔돈 0
-> 반환할 잔돈이 없을 때, 잔돈을 받아가지 않았을 때 예외 처리가 필요할 듯!

요구사항 중 하나인 음료 여러 개 구매가 안 됨!
- 한번에 하나만 선택이 가능한데, 의도한 건가용??

2022-06-20 11:36 UTC, nan-noo commented on public/manifest.json
> +  "name": "Create React App Sample",
얘네도 바꿔도 좋지 않을까요!

2022-06-20 11:36 UTC, nan-noo commented on src/index.css
> +}
이 파일은 안 쓰는 것 같은데, 지워도 괜찮지 않을까요?!

2022-06-20 11:36 UTC, nan-noo commented on src/components/DrinkSection/index.jsx
> +      }, 1000);
요것도 상수로 빼면 좋지 않을까요?

2022-06-20 11:36 UTC, nan-noo commented on src/components/DrinkSection/index.jsx
> +        });
```suggestion
        setIngredientList((prevIngredientList) => [...prevIngredientList, ingredient]);
```

2022-06-20 11:36 UTC, nan-noo commented on src/components/GuideMessage.jsx
> +export default GuideMessage;
단순히 렌더링만 하는 역할인데도, useEffect가 너무 많이 사용되는 것 같아서 한 번 간단하게 바꿔봤습니다!
기존에 있던 guideText state와 useEffect 두 개를 모두 삭제했습니다.
```suggestion
import { ORDER_PROGRESS } from "../constants";
import menus from "./../constants/menus";

function GuideMessage({ customerCharge, order: { progress, orderedMenu } }) {
  const updateOnOrderPending = () =>
    customerCharge.value >=
    Math.min(...Object.keys(menus).map((menu) => menus[menu].price))
      ? "원하는 음료를 선택하세요."
      : "투입 금액이 부족하여 선택 가능한 음료가 없습니다.";

  const updateOnOrderMaking = (menu) => `${menus[menu].name} 준비 중...`;

  const updateOnOrderComplete = (menu) => `${menus[menu].name} 나왔습니다. 😉`;

  const renderGuideText = () => {
    switch (progress) {
      case ORDER_PROGRESS.PENDING:
        return updateOnOrderPending();
      case ORDER_PROGRESS.MAKING:
        return updateOnOrderMaking(orderedMenu);
      case ORDER_PROGRESS.COMPLETE:
        return updateOnOrderComplete(orderedMenu);
      default:
    }
  };

  return <p className="guide text">{renderGuideText()}</p>;
}

export default GuideMessage;

```

대충 확인했을 때 버그는 없는 것 같은데, 어떻게 생각하나요?? 
useEffect는 되도록 쓰지 말고, state도 꼭 필요한 경우 아니면 props를 가져다 어떻게든 쓰자라는 생각입니당

2022-06-20 11:36 UTC, nan-noo commented on src/constants/index.js
> +  COMPLETE: 300,
이거 100, 200, 300으로 한 이유가 있을까요?? 그냥 한 건가요??

2022-06-20 11:36 UTC, nan-noo commented on src/hooks/useCustomerCharge.js
> +    resetReturnedChange,
평소에 귀찮아서 setCustomCharge를 return하도록 했는데, 소피아의 이런 패턴 본받아야겠어요..! 함수명도 더 구체적이라 이해하기 편하네용

2022-06-20 11:36 UTC, nan-noo commented on src/hooks/useOrder.js
> +    progress: ORDER_PROGRESS.PENDING,
저는 setTimeout id로 leading edge를 적용했는데, 요런 상태를 저장하는 것도 좋네용!

2022-06-20 11:36 UTC, nan-noo commented on src/components/ChargeSection/ChargeAmountSection.jsx
> +  const handleClickReturnChangeButton = (e) => {
인자로 들어간 e는 안 쓰는 것 같네요!
궁금한게, 새로운 로직이 없음에도 그냥 returnAllCustomerCharge를 쓰지 않고 handleClickReturnChangeButton안에 returnAllCustomerCharge를 넣어서 감싸주는 이유는 무엇인가요? 통일성인가용??

2022-06-20 11:38 UTC, nan-noo commented on src/components/GuideMessage.jsx
> +export default GuideMessage;
더 줄이려면 더 줄일수도 있을 것 같네요!

2022-06-20 14:49 UTC, soyi47 commented on public/manifest.json
> +  "name": "Create React App Sample",
좋아요! 수정했습니다!

(아래는 슥삭 훑어본 참고자료)
https://web.dev/add-manifest-react/
https://developer.mozilla.org/ko/docs/Web/Manifest

2022-06-20 14:49 UTC, soyi47 commented on src/index.css
> +}
맞습니다! 안 그래도 오늘 다시 보다가 지웠어요. 👍

2022-06-20 14:54 UTC, soyi47 commented on src/components/DrinkSection/index.jsx
> +      }, 1000);
시간 간격 1000ms 말하는 게 맞나요?
여기 setTimeout, 여기 파일에서만 사용될 상수라 해당 파일 상단에 상수로 빼줬습니다~

2022-06-20 14:54 UTC, soyi47 commented on src/components/DrinkSection/index.jsx
> +        });
오 짧고 좋네요. 바로 적용해야짓

2022-06-20 15:16 UTC, soyi47 commented on src/components/GuideMessage.jsx
> +export default GuideMessage;
태태 생각에 완전 동의합니다! 리팩토링이 너무 부족했네요.
저도 상태의 수는 최대한 줄이고 useEffect 사용도 최대한 지양하는 게 좋다고 생각해요. 
(useEffect라는 이름부터 별로 안 쓰고 싶달까요...?) 

태태가 제안해준 방식을 참고하면서, useMemo를 이용하여 코드 라인을 확 줄여봤습니다.

2022-06-20 15:17 UTC, soyi47 commented on src/constants/index.js
> +  COMPLETE: 300,
예,,, 이유 없습니다. 그냥 숫자로 해보고 싶어서 해봤어요.

2022-06-20 15:20 UTC, soyi47 commented on src/hooks/useCustomerCharge.js
> +    resetReturnedChange,
저두 너무 급할 땐 바로 setState를 반환할 것 같네요... 😂
구체적으로 적어주면 확실히 갖다 쓰기도, 이해하기도 편해서 좋더라고요!

2022-06-20 15:38 UTC, soyi47 commented on src/hooks/useOrder.js
> +    progress: ORDER_PROGRESS.PENDING,
오,, 어떻게 한 건지 궁금해서 방금 태태 코드 보고 왔습니다. ref를 사용해서 setTimeout id를 저장했군요!
그런데 leading edge를 적용했다는 건 무슨 뜻인가요~? 내일 만났을 때 물어볼테니 이야기해주세용 🥰

2022-06-20 15:48 UTC, soyi47 commented on src/components/ChargeSection/ChargeAmountSection.jsx
> +  const handleClickReturnChangeButton = (e) => {
1. 인자로 받은 e를 안 쓰는 경우에는 지워주도록 할게요!
2. 맞아요! 일관성이 가장 큰 이유입니다. 여러 함수 호출이 있는 경우에 핸들러 함수를 따로 정의해주었기 때문에, 일관성 있게 하나의 함수만 호출하더라도 핸들러 함수로 감싸주었어요. 
또 개인적인 취향으로도 하나의 함수만 호출하더라도 핸들러로 감싸주는 걸 좋아해요. 둘을 분리해주는 게, 함수 이름과 그 내부를 봤을 때 바로 의미 파악이 더 잘 되는 느낌이더라고요. '이벤트 핸들러 함수구나! -> 내부에서는 요런 동작이 이루어지는구나!'

2022-06-22 04:16 UTC, soyi47 commented
안녕 태태! 
코멘트에 수정한 커밋 링크 추가해뒀어요. PR이 닫혀서 개인 레포 링크로 달아뒀습니다. 궁금하면 확인해보십쇼!
태태의 꼼꼼한 리뷰 너무 좋아 💕 또 만납시다!

---

> 저도 이거 고민중입니다! 꼭 전역 상태가 아니라도 drilling이 깊어지는 상황에선 부분적으로 사용해도 좋다고 생각해요!

좋아요! 요구사항 7에서는 Context API 적용해보려고 합니다!

> 저랑 비슷한 네이밍이라 전 좋았습니당 :D 아직까진 헷갈리는 부분도 없고, Section이 좀 걸린다면 폴더명 말고 파일명에선 Section을 없애도 괜찮지 않을까요?!

태태도 보기에 괜찮다고 하니 일단 컴포넌트 이름은 이대로 두고, 작업하면서 더 좋은 이름이 생각나면 수정해볼게요! 👍

- input이 하나임에도 form으로 감싼 이유
form의 submit 이벤트, 즉 엔터 입력에 대한 처리를 사용하고 싶어서 사용해주었어요. form의 제공하는 유효성 검증도 사용할 수는 있겠지만, 금액 충전 컴포넌트에서는 필요성을 못 느꼈어요!

- 에러 해결
남아있는 잔돈에 대한 처리가 제대로 되지 않은 문제라고 파악했어요! 잔돈을 가져가기 전까지는 잔돈이 그대로 남아있도록 바꾸어, 잔돈 받아가기 버튼을 눌렀을 때 잔돈이 초기화되지 않도록 수정했습니다. 찾아줘서 고마워요! 🥰 https://github.com/soyi47/2022-looking-for-the-sound-of-an-object/commit/f624fe0913b1469acf9100767bdfe4f214913716

- 요구사항과 관련하여
'돈을 충분히 넣고 한번에'라는 표현에서 다르게 해석할 수 있을 것 같아요! 저는 '한번에'를 돈을 한번에 많이 넣고 나면, 연속해서 음료를 주문할 수 있도록 하라는 요구사항으로 파악했어요. 예를 들어, 만원 충전 -> 천원 음료 구입 및 받기 -> 2천원 음료 구입 및 받기 -> 2천원 음료 구입 및 받기 ... 이렇게 충전 한번에 여러 메뉴를 구입할 수 있는 방식으로 생각한거죠. 돈을 넣고, 여러 음료를 고른 다음 한번에 여러 메뉴 주문을 넣고 차례대로 음료를 받는 방식보다는, 지금 방식이 자판기 커피 뽑아 먹을 수 있는 그,,, 자판기 같다고 생각되어서요!