[요구사항 7] 소피아 제출합니다 🍉
woowacourse-study/2022-looking-for-the-sound-of-an-object pull request #25
Opened 2022-06-25 07:50 UTC by soyi47

2022-06-26 08:08 UTC, moonheekim0118 requested changes
![](https://c.tenor.com/zVSfEx73hEcAAAAC/greeting.gif)
안녕하세요 소피아 : D 
컴포넌트 구조가 너무 깔끔해서, 코드 읽기가 쉬웠고, 이해하기도 매우 수월했습니다!
Context API 도 잘 사용해주어서 코드 간 의존성이 많이 분리되었네요!

타입스크립트 같은 경우도 너무 잘 사용해주셨는데! `as` 대신 타입가드를 구현해보면 어떨까요?!
그 외에는 정말 너~~무 깔끔합니다 👍 👍  역시 소피아.. ❤️ 
방학동안 너무 수고하셨구 레벨 3 화이팅!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2022-06-26 08:08 UTC, moonheekim0118 commented on src/type.ts
> +}
`keyof typeof menus` 가 여러군데에서 사용되는데, 아예 타입에 저장해서 재사용하는건 어떨까요?
```ts
type Menu = keyof typeof menus;
```

2022-06-26 08:08 UTC, moonheekim0118 commented on src/context/CustomerChargeContext.tsx
> +export const CustomerChargeProvider = ({ children }: Props) => {
저는 children props 은 따로 타입핑 안해주고, `PropsWithChildren`을 사용하는데! 어떠신가요??
지금은 props 로 받아오는 값이 children 밖에 없어서 `unknown` 으로 해주었지만 나중에 Props 가 추가되면 저 자리에 interface 를 넣어주면 되더라구요! 근데 이건 취향차이라 ㅎㅎ 
```suggestion
export const CustomerChargeProvider = ({ children }: React.PropsWithChildren<unknown>) => {
```

2022-06-26 08:08 UTC, moonheekim0118 commented on src/components/ChargeSection/TakeChangeSection.tsx
> +  );
이 부분도 따로 훅으로 만들수 있지 않을까요 ?!
Context 를 사용할 때 마다 해당 Context (CustomerchargeContext) 를 가져오고, useContext 를 훅을 불러주는 것 보다, Context 별로 사용하는 커스텀훅을 만들어주면 간편할 것 같아요!

```tsx
const { customerCharge, resetreturnChange } = useCustomerChargeContext();
```

이렇게요!

https://kentcdodds.com/blog/how-to-use-react-context-effectively
관련 아티클 추천합니다 : D

2022-06-26 08:08 UTC, moonheekim0118 commented on src/components/ChargeSection/ChargeAmountSection.tsx
>    };
Input type 이 넘버면 Number 로 변환해주지 않구 `e.target.valueAsNumber` 를 사용해볼 수도 있지 않을까요? 👀

2022-06-26 08:08 UTC, moonheekim0118 commented on src/components/DrinkSection/DrinkMenuSection.tsx
> +
assertion 하지 않고 더 안전하게 name 이 Menus 중에 하나인지 확인할 방법은 없을까요 🧐

2022-06-26 08:08 UTC, moonheekim0118 commented on src/components/DrinkSection/index.tsx
>    const [ingredientList, setIngredientList] = useState([]);
타입을 더 쪼여줍시다!! 
```suggestion
  const [ingredientList, setIngredientList] = useState<string[]>([]);
```

2022-06-26 08:08 UTC, moonheekim0118 commented on src/components/DrinkSection/DrinkMenuSection.tsx
> +          </button>
toLocalString() 같은건 유틸로 빼주는게 어떨까요 ? 👀 명세가 변경되어서, 금액을 다듬는 로직이 변경될 수 있는데, 개발자가 이를 찾아서 하나하나 바꾸긴 힘들 것 같아요!

2022-06-26 08:08 UTC, moonheekim0118 commented on src/components/DrinkSection/index.tsx
> +    const drink = menus[menuName] as unknown as Drink;
`as unknown as Drink` !!
음..이 부분도 menus[menuName] 이 정확히 Drink 타입인지 타입 가드를 넣어주는 방향으로 수정할 수 있지 않을까요? 
`instaceof ` 를 사용하면 될 것 같은데, menus 가 `readonly`라서 어렵긴 할 것 같아요 ㅠ.ㅠ..흑흑..타스 어렵다!!

2022-06-26 08:08 UTC, moonheekim0118 commented on src/components/DrinkSection/DrinkMenuSection.tsx
> +          </button>
<br/ > 태그를 사용해서 text 두개의 위치를 정해주는 것 보다 아예 p tag 로 감싸는게 어떨까요?ㅎㅎㅎ

2022-06-26 08:08 UTC, moonheekim0118 commented on src/components/GuideMessage.tsx
> +  }, [customerCharge.value, orderedMenu, progress]);
useMemo 사용 좋아요! 👍 👍 👍 
제가 포코한테 받았던, 리뷰에 다르면 useMemo 사용할 때는 리액트 devtools 컴파일러로 성능 차이를 확인하구 사용하라구 하네요! ㅎㅎ

2022-06-27 16:26 UTC, moonheekim0118 commented
일단 머지 할게요 소피아 :)
수고하셨구 다음 단계에서 반영해주시면 될 것 같아요! 
레벨3 화이탱 ❤️

2022-06-27 16:26 UTC, merged

2022-07-03 12:54 UTC, soyi47 commented on src/context/CustomerChargeContext.tsx
> +export const CustomerChargeProvider = ({ children }: Props) => {
와앙 요런 아이가 있었군요! 
`React.PropsWithChildren<{}>` 이렇게 적용해주면 unknown을 사용하지 않고도 쓸 수 있네요!
배워갑니다! ><

https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/context/#extended-example

2022-07-03 12:55 UTC, soyi47 commented on src/type.ts
> +}
좋아요~ 적용해봤습니다!

2022-07-06 10:50 UTC, soyi47 commented on src/components/DrinkSection/DrinkMenuSection.tsx
> +
이 뒤에서 아래와 같은 함수로 체크해주는 방법이 생각나는데, 더 좋은 방법 있을까요?

```
function isMenu_function(value: string): value is Menu {
  return Object.keys(menus).includes(value);
}
```