[요구사항 7] 도리 제출합니다 🍉
woowacourse-study/2022-looking-for-the-sound-of-an-object pull request #26
Opened 2022-06-25 17:02 UTC by prefer2

안녕하세요 리뷰어 하리님(@LAH1203) 만나뵙게 되어서 영광입니다. 내일 리뷰어님과 식사를 할 생각에 떨려서 잠이 안오네요

![image](https://user-images.githubusercontent.com/67692759/175782899-86954ab4-9dfb-4b2c-91f2-32d582fb79ec.png)

### [☕️도리의 자판기](https://prefer2.github.io/2022-looking-for-the-sound-of-an-object/)

요구사항이 사이다와 콜라를 추가한다인 만큼 구조적으로는 크게 변한 것이 없습니다.

타입스크립트를 사용하기는 했는데 역시나 어렵더군여. 구글링과 vscode의 힘을 빌려 어찌저찌 해보기는 했는데 잘 모르겠네요. TS관련해서 많은 채찍질 부탁드립니다 선구자님.

저번 리뷰를 담당하면서 제가 `디스펜서`의 역할을 너무 무시했다라는 생각이 들더라고요. 그래서 이 점을 보안해보았습니다. 아직 redux를 쓸만큼 복잡하지는 않은 구조라 생각되어 prop-drilling으로만 작성해보았어요. 음료가 만들어지는 동안에는 금액 투입이나 반환이 불가능합니다(button disable 해놓았습니다) 원래는 dispenser component로 묶어서 쓸려고 했는데 생각해보니 ui만 같을뿐인 것 같아 따로 만들어주었습니다.

외에는 간단한 상수화나 스타일 변화정도가 다입니다. 몰랐는데 제가 main branch에다가 다 때려박고 있었더라고요. 이런이런. 다음부터는 브랜치 이쁘게 나눠서 작성해보도록 할께욥~~

2022-06-26 08:17 UTC, LAH1203 requested changes
도리도링~ 리뷰 왔숩니당 🐠

<img src="https://user-images.githubusercontent.com/57928612/175805670-b445d5eb-849e-441e-8680-4a78e54b3ec3.png" alt="Cute Dori" width="300" />

타입스크립트 적용 잘 하셨는데요 ?! 귯귯 좋았습니당

저는 에러는 아니구 좀 더 추가했으면 좋았을 것들에 대해서 리뷰를 남겨봤습니당 후후

코멘트 확인하시고 천천히 답 주세요 🥰 혹시 바로 머지 원하시면 코멘트나 DM 주세요!

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/VendingMachine.tsx
> +  const [vendingMachineState, setVendingMachineState] = useState(STATUS.READY);
`vendingMachineState`에는 STATUS만 들어가니, STATUS의 value 기반으로 타입을 만들어서 타입 정의를 해주면 어떨까요?

hint: 객체의 value만을 뽑아와서 타입을 만드는 방법 🥯

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/VendingMachine.tsx
> +            onClick={() => handleMenuClick(key as DrinkType, value.price)}
`handleMenuClick`에 커링을 적용해보는건 어떨까요? 그러면 익명 함수를 사용하지 않아도 될 것 같아용

```ts
const handleMenuClick = (name: DrinkType, price: number) => () => {
  setVendingMachineState(STATUS.WORKING);
  setDrink(name);
  setTotalMoney((prev) => (prev -= price));
};

  ...

    onClick={handleMenuClick(key as DrinkType, value.price)}

  ...
```

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/components/Button/index.tsx
>  interface ButtonType {
그거 아시나요? HTML Button의 어트리뷰트를 정의해놓은 타입도 있답니다 😈

[참고](https://stackoverflow.com/questions/40731352/extending-html-elements-in-react-and-typescript-while-preserving-props)

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/components/CoinDispenser/index.tsx
> +type coinType = 500 | 100 | 50 | 10;
`initialCoins`, `coinArray`, `coinType`에서 동일한 500, 100, 50, 10을 사용하네요!
한 가지 값을 정하고 그걸 모두가 가져다 사용할 수 있도록 바꿔볼까요?

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/components/CoinDispenser/index.tsx
> +  while (money > 0 && index < 4) {
요 부분은 한번 좀 더 우아하게 리팩토링을 시도해보는건 어떻게 생각하시나용?

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/components/CoinDispenser/index.tsx
> +      // 이 부분이 맘에 안듭니다
흠 요 부분에서 아마 가장 많이 신경쓰이는 부분은 `key as unknown as coinType`이 반복되는 부분일 것 같아요.
그래서 우선 `Object.keys`를 통해 나오는 값이 String[]가 아니라 coinType[]이 될 수 있도록 만들어봤는데요! 이건 어떠신가요 ?!

```ts
setCoins(prev => 
  (Object.keys(prev) as unknown as Array<keyof typeof prev>).reduce(
    (acc, key) => {
      acc[key] = changedCoins[key] + prev[key];
      return acc;
    },
    { ...initialCoins },
  ),
);
```

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/components/DrinkDispenser/index.tsx
> +import { DrinkType, recipes, STATUS } from "../../constants";
절대 경로를 써보는 것도 좋겠네요!

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/components/DrinkDispenser/index.tsx
> +  drink: DrinkType | undefined;
뒤에 ` | undefined`는 뭔가요? drink가 들어오지 않을 경우인가용?

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/components/DrinkDispenser/index.tsx
> +    if (drink) {
요 부분은 early return을 시켜봐도 좋을 것 같아요 👀

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/components/DrinkDispenser/index.tsx
> +  @keyframes drop {
styled-components에서 지원하는 keyframes를 사용해보면 어떨까요?

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/components/Menu/index.tsx
> +      <div>{price.toLocaleString("ko")}원</div>
👮‍♂️

![image](https://user-images.githubusercontent.com/57928612/175805236-a7794b63-5dc3-42f4-9b9c-700c7ee9ea83.png)

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/components/MoneyDisplay/index.tsx
> +      총액: {children?.toLocaleString("ko")}원
👮‍♂️

![image](https://user-images.githubusercontent.com/57928612/175805236-a7794b63-5dc3-42f4-9b9c-700c7ee9ea83.png)

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/components/MoneyInput/index.tsx
>  interface MoneyInputType {
요기도 마찬가지로 제공해주는 input attribute type을 쓸 수 있겠네요! 물론 사용은 자유.. 🌟

2022-06-26 08:17 UTC, LAH1203 commented on react-vending-machine/src/constants/index.ts
> +export type DrinkType =
한 번 위의 drinks 배열로 DrinkType을 만들어볼까요?

또, 이런 type 정의는 types 폴더를 따로 만들어서 관리를 해보는 건 어떻게 생각하시나요? 😉

2022-06-27 03:15 UTC, prefer2 commented on react-vending-machine/src/VendingMachine.tsx
> +  const [vendingMachineState, setVendingMachineState] = useState(STATUS.READY);
https://dev.to/smeijer/a-typescript-valueof-implementation-and-how-it-s-built-4gim
이런 방법이 있군요! TS 보면 볼수록 멋진 방법들이 많네요. 위 블로그를 보고 ValueOf를 만들어서 사용해보았어요. [7527601](https://github.com/woowacourse-study/2022-looking-for-the-sound-of-an-object/pull/26/commits/7527601f926a0a337e5c7d14272dc3f1269a5ac1)
(그나저나 전역상태 관리 없이 TS로 작성하다보니 전달하는 함수나 이런것들 type 지정하기 매우 어렵네요 😂)
혹시 더 좋은 방법이 있다면 알려주세욥!!

2022-06-27 03:25 UTC, prefer2 commented on react-vending-machine/src/VendingMachine.tsx
> +            onClick={() => handleMenuClick(key as DrinkType, value.price)}
하리가 제안해준 방식으로 변경하는게 좀 더 일관성 있는 것 같네요! 같은 방법에 순서의 차이이기는 한데 하리는 평소에 매개변수 전달할 때 커링을 주로 사용하나요?? 궁금궁금. 저는 습관적으로 인수전달은 위의 방식으로 했던 것 같아요. https://ko.reactjs.org/docs/handling-events.html

2022-06-27 05:05 UTC, prefer2 commented on react-vending-machine/src/components/Button/index.tsx
>  interface ButtonType {
아닛 세상에 이런일이 너무 좋네요~~ 최고최고

![image](https://user-images.githubusercontent.com/67692759/175863832-a28c565a-cf8e-4983-a4cd-d4fac077be25.png)

2022-06-27 05:13 UTC, prefer2 commented on react-vending-machine/src/components/CoinDispenser/index.tsx
> +      // 이 부분이 맘에 안듭니다
오옷 그렇네요 위에서 한번에 처리하면 훨 깔끔~ 이거였어 내가 찾던것! 😘

2022-06-27 05:24 UTC, prefer2 commented on react-vending-machine/src/components/CoinDispenser/index.tsx
> +  while (money > 0 && index < 4) {
왜... 이렇게 짰을까요? 역시 졸릴때는 코드 짜면 안되 [046f113](https://github.com/woowacourse-study/2022-looking-for-the-sound-of-an-object/pull/26/commits/046f113c310fade29fa9e71b150cbc2de84b5272)

2022-06-27 05:25 UTC, prefer2 commented on react-vending-machine/src/components/DrinkDispenser/index.tsx
> +  drink: DrinkType | undefined;
yes.... 음료가 없을때를 위해 해놓았습니당

2022-06-27 05:26 UTC, prefer2 commented on react-vending-machine/src/components/DrinkDispenser/index.tsx
> +    if (drink) {
그게 더 깔끔하겠네요 👍

2022-06-27 05:27 UTC, prefer2 commented on react-vending-machine/src/components/MoneyInput/index.tsx
>  interface MoneyInputType {
i lov it

2022-06-27 11:53 UTC, LAH1203 commented on react-vending-machine/src/VendingMachine.tsx
> +  const [vendingMachineState, setVendingMachineState] = useState(STATUS.READY);
오호! 제네릭으로 `ValueOf`를 생성한 것 좋네요 👏
여기서 한 가지만 더 한다면, STATUS의 value를 타입화시킨게 여러 파일에서 있으니 다른 곳에서 타입으로 지정하고 이를 가져다가 사용해도 좋을 것 같아요 (휴먼 에러 방지용 !)

저도 Props 타입 정의할 때 함수가 참... 어렵더라고요....? 🥲
setState도 그냥 `() => void`로 적곤 했는데, 도리 덕분에 `Dispatch<SetStateAction<stateType>>`도 알게 되었어요 😆
굿굿~

2022-06-27 12:09 UTC, LAH1203 commented on react-vending-machine/src/VendingMachine.tsx
> +            onClick={() => handleMenuClick(key as DrinkType, value.price)}
흠 저는 이벤트핸들러에 매개변수를 전달한 기억이 거의 없어서, '뭘 많이 사용한다' 그런 건 많이 없는 것 같아요.
요 코멘트를 남겼던 것은 도리가 말씀해주신대로 일관성 있게 사용하면 좋을 것 같다는 생각이었습니다 ㅎㅎㅎ
만약에 사용한다면 저는 커링 방식을 더 애용할 것 같아요! 멋있어서,, 😎

2022-06-27 12:20 UTC, LAH1203 commented on react-vending-machine/src/components/DrinkDispenser/index.tsx
> +  drink: DrinkType | undefined;
아하.. 그러면은 옵셔널을 써도 될 것 같아요!
https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#use-optional-parameters

2022-06-27 12:23 UTC, LAH1203 commented on react-vending-machine/src/components/Menu/index.tsx
> +      <div>{price.toLocaleString("ko")}원</div>
(도리와 월터 리뷰어님과의 즐거운 👮‍♂️ 추억...)

```suggestion
      <div>{price.toLocaleString("ko-KR")}원</div>
```

부분을 말하려고 그랬습니다...ㅎ

2022-06-27 12:30 UTC, LAH1203 approved these changes
🪨2️⃣🪨2️⃣~ 우선 오늘까지 머지를 해야한다고 해서 하러왔습니당

저는 다음에도 도리를 리뷰하더라고요?
만약 반영할 것이 있다면 그 때 마저 반영해주세요! 이번에는 바빠서 타입스크립트 위주로밖에 보지 못했는데, 그 때는 다른 부분에서도 좀 더 보도록 하겠습니다 😏

내일 같이 레벨 인터뷰 퐈이팅합시다...😋

2022-06-27 12:30 UTC, merged