[요구사항 1] 샐리 제출합니다☕️
woowacourse-study/2022-looking-for-the-sound-of-an-object pull request #3
Opened 2022-04-11 12:45 UTC by liswktjs

안녕하세요 여러분... 마감시간 착각한 샐리입니다 🥲

완성하고 소피아와 하리가 만든 페이지를 보고 나서 무언가 잘못되었다는 것을 알았지만 되돌리기에는 시간이 늦어서 일단 제출합니다 하하😇

### <a href="https://liswktjs.github.io/2022-looking-for-the-sound-of-an-object/">데모 페이지</a>

## 📣 객체의 소리를 찾아서 
README에 적어두기는 했지만 보시기 편하게 이곳에도 써보겠습니다 
방학을 시작하다보니 기분이 좋아져서 혼자 만담을 하게 되었네요😅 

자판기 넌 정체가 뭐야? 말해봐!

집에서 버튼 누르면 커피 나오는 기계니?, 길거리에서 돈 받고 커피 파는 기계니?

자판기의 정의: <a href="https://ko.dict.naver.com/#/search?query=%EC%9E%90%ED%8C%90%EA%B8%B0">사람의 손을 빌리지 아니하고 상품을 자동적으로 파는 장치</a>

음...🤔 돈을 받아야만 하는 건가? 수익성 없는 자판기 일 수도 있잖아!

👂 뭐? 뭐라고? 이번에 돈 안 받는다고? 오 좋아 일단 1단계 자판기야 너는 수익성 없는 거야 돈 넣는게 없는 거야 난 그렇게 들렸어! 😎 우리 약속했다?🤝 후후

그러면 이제 내가 버튼을 누르면 컵이 나오고, 에스프레소, 뜨거운 물이 나오는 걸로 되겠구나

아 그러면, 컵 수량이랑 에스프레소, 뜨거운 물 양 관리하는거 필요하지 않겠어?

너는 컵 만드는 기계가 아니니깐 들어 있는 컵만 써야지, 원두도 내가 사다가 채워줘야 하지,
.<br>
.<br>
.<br>
너 은근 손이 많이 들어가는 구나? 😕 (나중에는 청소도 해달라고 하겠어😡)

물은 그냥 정수기에 연결된 거 쓰자 물 정도는 너가 데울 수 있잖아 ^^

자 보자 보자 그러면, 너는 지금 컵이랑 에스프레소 원두 관리하는 store 필요하구나. 컵이랑, 에스프레소 충전 해주는 기능도 필요하고 갑자기 피곤해지는 걸? 너란 녀석... ^^

엇, 잠깐만 만약에 store에 컵이랑 에스프레소 원두 없으면 그냥 가만히 있을 것 아니지? 유저가 당황해서 너 고친다고 마구 마구 때릴 수도 있다고! 아니면 버튼 무지하게 누르거나 🤬

내가 특별히 너의 안전을 위해서 컵 또는 에스프레소 원두가 없을 경우에 유저에게 알려주겠어 고마워 하라고! 😏

## 객체와 합의 본 사항 📝

~~합의 맞습니다... 아무튼 맞아요~~

- [x] 최초에 보여지는 화면에는 커피의 주문 가능한 수량과 커피를 주문하는 버튼이 보여진다.

- [x] 커피 주문 버튼을 누르면, 에스프레소가 추출되어 디스펜서로 나온다.

  - [x] 만약, 컵의 수량이나 에스프레소 원두 둘 중 하나가 0이라면, 커피의 주문 가능한 수량은 0이다.
  - [x] 커피의 주문 가능한 수량이 0임에도 버튼을 누를 경우 snackbar로 유저에게 상황을 알린다.
  - [x] 에스프레소가 성공적으로 나온 경우, dispenser 로 이를 알린다.

- [x] 원두와 컵 충전 탭을 누르면 해당 페이지로 이동한다.

- [x] 원두, 컵 충전 탭에서 유저는 원두와 컵을 충전할 수 있다.

  - [x] 입력된 원두, 컵 수량이 0 이하 일 경우 snackbar로 충전 불가능함을 알린다
  - [x] 입력된 원두, 컵 수량이 소수점 값일 경우 snackbar로 충전 불가능함을 알린다
  - [x] 입력된 원두, 컵 수량이 비어있을 경우 snackbar로 충전 불가능함을 알린다

- [x] 원두의 수량과 컵의 수량은 localStorage에서 관리 한다.

## 생각해본 것들  🤔

만들면서 바로 직전에 했던 자판기 과제와 매우 비슷하게 구조를 짜고 있다는 생각이 들었습니다. 

물론 똑같은 자판기니깐? 비슷할 수 있을 수도 있지만 이 아이만의 소리를 못들은 것 같아 살짝 아쉽습니다ㅠ 

그리고 너무 앞서서 생각을 했나? 라는 생각도 드네요 (성격이 여기서 나오는..) 
첫 과제인데 뭔가를 많이 해버렸네요 

소피아, 하리 앞으로 잘부탁드려요~🙇‍♀️

2022-04-11 13:47 UTC, soyi47 commented
샐리의 자판기는 정말 현실의 자판기와 같이 손이 많이 가네요. 😂 상당히 깊은 대화를 나누셨군요..!

2022-04-11 14:34 UTC, liswktjs commented
> 샐리의 자판기는 정말 현실의 자판기와 같이 손이 많이 가네요. 😂 상당히 깊은 대화를 나누셨군요..!

제가 너무 과몰입을 해버려서 찐하게 진실의 방 가서 대화좀 하고 왔습니다 하하

2022-04-11 15:59 UTC, LAH1203 requested changes
샐리 안녕하세요! 하리입니다 🤗
저도 코드 리뷰는 처음이라 제대로 했는지 잘 모르겠네요,,ㅎ 우선 샐리의 의도가 궁금했던 점 위주로 질문 남겨보았습니다 😄
샐리의 코드 양과 결과물이 어마무시해서 살짝 코멘트 수가 있네요 😅 너무 잘해주셔서 간신히 짜내보았읍니다,, 🤣
편하실 때 답변 주세요 :)

2022-04-11 15:59 UTC, LAH1203 commented on docs/README.md
> +  - [x] 입력된 원두, 컵 수량이 0 이하 일 경우 snackbar로 충전 불가능함을 알린다
0 이하일 경우 스낵바로 알린다고 해주셨는데, 0이나 -0을 입력했을 때는 스낵바가 나오지 않고 있어요!
스낵바 메시지를 봤을 때도 0 이상을 정상 경우라고 판단하고 있는 것 같은데, 기능 요구사항과 맞지 않아서 통일이 필요할 것 같아요 🤔

2022-04-11 15:59 UTC, LAH1203 commented on index.html
> +<html lang="kor">
오 여기 오타가..! `r`이 잘못 들어갔네요 👀

2022-04-11 15:59 UTC, LAH1203 commented on index.html
> +        <h2 id="purchase-coffee-title" hidden>에스프레소 구매하는 탭</h2>
혹시 사용하지 않는 heading에도 id를 부여해준 이유가 있을까요?

2022-04-11 15:59 UTC, LAH1203 commented on src/components/CoffeeMachineComponent.js
> +    e.preventDefault();
보니까 모든 버튼 클릭 이벤트에 `e.preventDefault()`를 붙여준 것 같아요. submit 이벤트가 아니다보니 붙여주지 않아도 페이지가 넘어가는 일은 없을 것 같은데, 혹시 붙여준 이유가 따로 있을까요? 🤔

2022-04-11 15:59 UTC, LAH1203 commented on src/store/materialStore.js
> +      return JSON.parse(localStorage.getItem('materialStore'));
getItem한 것을 변수에 저장해서 사용하는건 어떻게 생각하시나요? 그러면 아래 같이 간결한 표현도 가능할 것 같아요 🙂

```js
getMaterialStore() {
  const item = localStorage.getItem('materialStore');
  return item ? JSON.parse(item) : 0;
}
```

2022-04-11 15:59 UTC, LAH1203 commented on src/styles/button.css
> +  border: 1px solid #fff;
지금 있는 'tab-button', 'purchase-button', 'recharge-button'의 속성 중 `height`와 `border`는 동일하게 가지고 있는 것으로 보여요! 위의 버튼 엘리먼트가 아니라 각자의 클래스에 나눠서 부여해주신 이유가 있을까요?

2022-04-11 15:59 UTC, LAH1203 commented on src/styles/index.css
> +  transition: transform 300ms ease-in-out;
오호 스낵바 애니메이션에 transform, transition을 사용하셨군요 👍

2022-04-11 15:59 UTC, LAH1203 commented on src/utils/constants.js
> +export const SHOW_SNACK_BAR_DELAY_TIME = 2000;
와 딜레이 시간까지 상수화를..! 존경합니다 샐리 선생님,, 👏👏

2022-04-11 15:59 UTC, LAH1203 commented on src/utils/showSnackBar.js
> +  return mention => {
오 이런 식으로 스낵바를 함수 리턴으로도 구현할 수 있군요! 신기하네요 😲

2022-04-11 15:59 UTC, LAH1203 commented on src/utils/validations.js
> +  return true;
샐리! 이럴 때 조건문으로 리턴하는건 어떻게 생각하세요?

```js
export const validateMaterialInput = userInput => {
  return userInput >= 0 && Number.isInteger(userInput);
};
```

2022-04-12 04:46 UTC, liswktjs commented on docs/README.md
> +  - [x] 입력된 원두, 컵 수량이 0 이하 일 경우 snackbar로 충전 불가능함을 알린다
앗 그런 에러가 있었군요! -0은 고려 해보지 못했어요 2단계에 반영해 보겠습니다 :)

2022-04-12 04:50 UTC, liswktjs commented on index.html
> +        <h2 id="purchase-coffee-title" hidden>에스프레소 구매하는 탭</h2>
section에서는 header가 존재해야 한다고 하더라고요. 이 해더를 aria-labelledby를 통해서 section과 연결을 해주기 위해서 id 값을 부여했습니다!

2022-04-12 04:51 UTC, liswktjs commented on src/components/CoffeeMachineComponent.js
> +    e.preventDefault();
같이 페어를 하신 분 중에 한 분이 습관처럼 붙이시더라고요 미연의 상황 방지? 같은 개념으로 그래서 저도 따라 해봤습니다:)

2022-04-12 04:51 UTC, liswktjs commented on src/store/materialStore.js
> +      return JSON.parse(localStorage.getItem('materialStore'));
오 좋아요 하리! 뭔가 쓰면서 찝찝했었는데 이거였어요!

2022-04-12 04:53 UTC, liswktjs commented on src/styles/button.css
> +  border: 1px solid #fff;
추후에 기능들이 추가 되면, 스타일 조정 들이 필요할 것 같아서 사전에 나누어 봤습니😆

2022-04-12 04:53 UTC, liswktjs commented on src/styles/index.css
> +  transition: transform 300ms ease-in-out;
스르륵 애니메이션 써보고 싶었습니다:) ㅎㅎ

2022-04-12 04:55 UTC, liswktjs commented on src/utils/showSnackBar.js
> +  return mention => {
이번에 자판기 미션에서 snackbar 구현을 setTimeout으로만 구현했었는데 여러번 클릭이 됐을 때 애니메이션에 제대로 동작하지 않는 에러가 발생하더라고요! 해결방법이 throttle debounce사용하는 거라고 해서 이번에 저도 처음 써봤습니다😎

2022-04-12 04:56 UTC, liswktjs commented on src/utils/validations.js
> +  return true;
오 좋아요 하리 뭔가 찝찝했었는데, 이렇게 줄일 수 있었는데 크으... 👍

2022-04-12 05:14 UTC, LAH1203 commented on index.html
> +        <h2 id="purchase-coffee-title" hidden>에스프레소 구매하는 탭</h2>
오 `aria-labelledby`! 사용해본적이 없어서 처음 알았네요 😲 굿굿!

2022-04-12 05:15 UTC, LAH1203 commented on src/components/CoffeeMachineComponent.js
> +    e.preventDefault();
오오 아주 좋은 습관인거 같아요! :)

2022-04-12 05:17 UTC, LAH1203 commented on src/styles/button.css
> +  border: 1px solid #fff;
오호 미래를 위한 장치! 좋아요 👍👍

2022-04-12 05:18 UTC, LAH1203 commented on src/utils/showSnackBar.js
> +  return mention => {
와 저도 같은 에러가 발생했었는데! 어쩐지 샐리의 스낵바는 에러 없이 잘 보이더라고요~~! 너무 좋네요 👍🏻 새롭게 배워갑니다 😆

2022-04-12 05:19 UTC, LAH1203 approved these changes
샐리, 피드백에 답변해주신거 확인했습니다! approve할게요~ 😁

2022-04-12 05:22 UTC, merged